### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by eviekek** [DS-Homebrew/shaberusoft-logging#1]
i downloaded this now my new 32dsi xl ll lite 32gb has turned into an airplane and i cant catch it its flying away very very quickly

**Comment by NightScript370** [comment]
Try SSH'ng into it (there's a vulnerability we found out about right after publicizing it) and downloading YouTube ID `dQw4w9WgXcQ`. That'll make it come down...although it might be more prone to dancing

**Comment by eviekek** [comment]
i used your tip but now its singing never gonna give you up and doing gangam style in the sky outside my window help

**Comment by NightScript370** [comment]
Why help? That's all we've ever wanted!
