### ISSUE TITLE
When run, DSi forcibly achieves sentience

### ISSUE THREAD

**Issue by sendhelpidfk** [DS-Homebrew/shaberusoft-logging#4]
After running some of Shaberusoft's catalog, I watched my DSi ssh into my desktop before curbstomping ChatGPT in a game of chess by simply launching an intercontinental ballistic missile. Should I be concerned, or is this intended behavior?

![image](https://github.com/DS-Homebrew/shaberusoft-logging/assets/55771438/6c1ab197-5c90-4b48-af56-59c8035bd50d)

**Comment by NightScript370** [comment]
AI is bad, so it is concerning. We would never expose our users to 6 fingered creations.
Maybe you got hacked?
