### ISSUE TITLE
how to convert 3ds card dumps to ntrb?

### ISSUE THREAD

**Issue by SNBeast** [DS-Homebrew/shaberusoft-logging#8]
i have a physical copy of monster hunter xx which i dumped but my 3ds isnt around and i need to play the game on real hardware to get nex dumps but i have a dsi and i heard about a year ago that nds-bootstrap can play 3ds games but whenever i try loading my dump it takes too long so i want to convert to a more optimized format but everyone tells me that you cannot convert 3ds card dumps to nds so the only option left is inflating the file to the large ntrb format but nobody i talked to knows anything about ntrb so i looked up "3ds inflation" but after spending a couple of minutes looking at the images there was nothing useful so i was wondering how do i inflate 3ds dumps please there is only a week left before nintendo network shuts down multiplayer

**Comment by NightScript370** [comment]
Cope
